# Generated by Django 5.0.4 on 2025-02-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='preferred_city',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='preferred_pincode',
            field=models.CharField(default=686506, max_length=10),
            preserve_default=False,
        ),
    ]
