# Generated by Django 5.0.4 on 2025-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0006_deliveryperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='last_location_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
