# Generated by Django 5.0.4 on 2025-03-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='fa-trophy', max_length=50)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_date', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achieved_milestones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
