# Generated by Django 5.0.4 on 2025-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('product', 'Product Update'), ('user', 'User Activity'), ('system', 'System Notification'), ('milestone', 'Milestone Achievement'), ('coupon', 'Coupon Reward')], max_length=20),
        ),
    ]
