# Generated by Django 5.0.4 on 2024-08-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
